language: objective-c
osx_image: xcode7.1
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
install: echo
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -workspace Stolpersteine.xcworkspace -scheme "Stolpersteine Bochum" -sdk iphonesimulator -configuration Debug | xcpretty -c && xcodebuild -workspace Stolpersteine.xcworkspace -scheme "Stolpersteine Berlin" -sdk iphonesimulator -configuration Debug test | xcpretty -c
