language: objective-c
script: 
  - xcodebuild -target "Stolpersteine Unit Tests" -sdk iphonesimulator -configuration Debug TEST_AFTER_BUILD=YES
  - xcodebuild -target "Stolpersteine Integration Tests" -sdk iphonesimulator -configuration Debug TEST_AFTER_BUILD=YES
