language: objective-c
install:
script: 
  - xcodebuild -workspace Stolpersteine.xcworkspace -scheme "Stolpersteine Tests" -sdk iphonesimulator -configuration Debug TEST_AFTER_BUILD=YES ONLY_ACTIVE_ARCH=NO
