language: objective-c
before_install:
  - gem install xcpretty
script: 
  - xcodebuild -workspace Stolpersteine.xcworkspace -scheme "Stolpersteine Berlin" -sdk iphonesimulator -configuration Debug test && xcodebuild -workspace Stolpersteine.xcworkspace -scheme "Stolpersteine Bochum" -sdk iphonesimulator -configuration Debug
